# -*- coding: utf-8 -*-
"""Imersao_dados_c/Python_alura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i52pr19jwzljcyBY0iSt5CpPT50OVdRb

# AULA 1 - Pandas
"""

# importando o pandas
import pandas as pd

#importando nosso dataset e nomeando ele como "df"
df = pd.read_csv('https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv')

#apresentando nossa dataset
df.head()

# da as informaçoes de cada coluna do nosso dataset
df.info()

df.describe()

# mostrar quantas linhas e colunas tem no nosso dataset
df.shape

linhas, colunas = df.shape[0], df.shape[ 1]
print("linhas: ", linhas)
print("colunas: ", colunas)

# apresentar as colunas do nosso dataset
df.columns

columns_translation = {
    'work_year' : 'ano',
    'experience_level' : 'senioridade',
    'employment_type' : 'contrato',
    'job_title' : 'cargo',
    'salary' : 'salario',
    'salary_currency' : 'moeda',
    'salary_in_usd' : 'usd',
    'employee_residence' : 'residencia',
    'remote_ratio' : 'remoto',
    'company_location' : 'empresa',
    'company_size' : 'tamanho_empresa',
}

df = df.rename(columns=columns_translation)
print(df.columns)

df["senioridade"].value_counts()

df["contrato"].value_counts()

df['remoto'].value_counts()

df['tamanho_empresa'].value_counts()

senioridade = {
    'SE' : 'Senior',
    'MI' : 'Pleno',
    'EN' : 'Junior',
    'EX' : 'Executivo',
}

df['senioridade'] = df['senioridade'].replace(senioridade)
df['senioridade'].value_counts()

contrato_mapping = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Meio Período',
    'FL': 'Freelancer'
}
df['contrato'] = df['contrato'].replace(contrato_mapping)
df['contrato'].value_counts()

tamanho_empresa = {
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
}
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)
df['tamanho_empresa'].value_counts()

remoto_mapping = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}
df['remoto'] = df['remoto'].replace(remoto_mapping)
df['remoto'].value_counts()

df.head()

df.describe(include='object')



"""# AULA 2 - Limpeza de Dados"""

df.isnull()

df.isnull().sum()

df['ano'].unique()

df[df.isnull().any(axis=1)]

import numpy as np

# criando um dataframe de teste
df_salrios = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', 'Val'],
    'salario': [4000, np.nan, 5000, np.nan, 100000]
})

# calcula a media e substitui os nulos
df_salrios['salario_media'] = df_salrios['salario'].fillna(df_salrios['salario'].mean().round(2))

# calcula a mediana e substitui os nulos pela a mediana
df_salrios['salario_mediana'] = df_salrios['salario'].fillna(df_salrios['salario'].median())

df_salrios

df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas['Preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()
df_temperaturas

df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas['Preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

df_cidades = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', 'Val'],
    'cidade': ['São Paulo', np.nan, 'Coritiba', np.nan, 'Belem']
})

df_cidades['cidades_preenchidas'] = df_cidades['cidade'].fillna('Não Informaddo')
df_cidades

df_limpo = df.dropna()

df_limpo.isnull().sum()

df_limpo.head()

df_limpo.info()

# convertendo o tipo do ano de float para int
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))

